from flask import Flask, render_template, request, redirect, url_for
import numpy as np
import matplotlib.pyplot as Plt
import io
import base64
from markupsafe import escape

app = Flask(__name__)

cultivars_info = {
'Mangang' : {"name": "Mangang", "korean_name": "만강", "it_number": "it1", "yield": 0, "img": "potatoes/Mangang.png", "pedigree": "pedigree/Mangang.png", "male": "IT244159", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Mangang_yield.png", "lw_graph": "graph/Mangang_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "late", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Gangseon' : {"name": "Gangseon", "korean_name": "강선", "it_number": "it2", "yield": 0, "img": "potatoes/Gangseon.png", "pedigree": "pedigree/Gangseon.png", "male": "Chubaek", "female": "DK1-83", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Gangseon_yield.png", "lw_graph": "graph/Gangseon_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Tamna' : {"name": "Tamna", "korean_name": "탐나", "it_number": "it3", "yield": 0, "img": "potatoes/Tamna.png", "pedigree": "pedigree/Tamna.png", "male": "Jeseo", "female": "AJ09", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Tamna_yield.png", "lw_graph": "graph/Tamna_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2014", "breeding_project": "Jeju provincial Agriculture Research Institute, Korea"},
'Dano' : {"name": "Dano", "korean_name": "다노", "it_number": "it4", "yield": 0, "img": "potatoes/Dano.png", "pedigree": "pedigree/Dano.png", "male": "KS13", "female": "Superior", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Dano_yield.png", "lw_graph": "graph/Dano_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2015", "breeding_project": "Wangsan seed company, Korea"},
'Golden Ball' : {"name": "Golden Ball", "korean_name": "골든볼", "it_number": "it5", "yield": 0, "img": "potatoes/Golden Ball.png", "pedigree": "pedigree/Golden Ball.png", "male": "DK1-116", "female": "DK1-110", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Golden Ball_yield.png", "lw_graph": "graph/Golden Ball_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'ArirangNo.1' : {"name": "ArirangNo.1", "korean_name": "아리랑1호", "it_number": "it6", "yield": 0, "img": "potatoes/ArirangNo.1.png", "pedigree": "pedigree/ArirangNo.1.png", "male": "DK1-117", "female": "Frontier", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/ArirangNo.1_yield.png", "lw_graph": "graph/ArirangNo.1_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'ArirangNo.2' : {"name": "ArirangNo.2", "korean_name": "아리랑2호", "it_number": "it7", "yield": 0, "img": "potatoes/ArirangNo.2.png", "pedigree": "pedigree/ArirangNo.2.png", "male": "DK1-116", "female": "Eigenheimer", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/ArirangNo.2_yield.png", "lw_graph": "graph/ArirangNo.2_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Oryun' : {"name": "Oryun", "korean_name": "오륜", "it_number": "it8", "yield": 0, "img": "potatoes/Oryun.png", "pedigree": "pedigree/Oryun.png", "male": "CIP705", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Oryun_yield.png", "lw_graph": "graph/Oryun_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2012", "breeding_project": "Gangwon probincial Agriculture Resrarch Institute, Korea"},
'Pungnong' : {"name": "Pungnong", "korean_name": "풍농", "it_number": "it9", "yield": 0, "img": "potatoes/Pungnong.png", "pedigree": "pedigree/Pungnong.png", "male": "Gumseo", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Pungnong_yield.png", "lw_graph": "graph/Pungnong_lw.png", "category": "Korean variety", "market": "French fry", "maturity": "late", "release_year": "2015", "breeding_project": "Gangwon probincial Agriculture Resrarch Institute, Korea"},
'Daegwang' : {"name": "Daegwang", "korean_name": "대광", "it_number": "it10", "yield": 0, "img": "potatoes/Daegwang.png", "pedigree": "pedigree/Daegwang.png", "male": "P3404-1", "female": "Haryeong", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daegwang_yield.png", "lw_graph": "graph/Daegwang_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2015", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Namjak' : {"name": "Namjak", "korean_name": "남작", "it_number": "it11", "yield": 0, "img": "potatoes/Namjak.png", "pedigree": "pedigree/Namjak.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Namjak_yield.png", "lw_graph": "graph/Namjak_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "1876(1961)", "breeding_project": "Irish Cobbler"},
'Sinnamjak' : {"name": "Sinnamjak", "korean_name": "신남작", "it_number": "it12", "yield": 0, "img": "potatoes/Sinnamjak.png", "pedigree": "pedigree/Sinnamjak.png", "male": "Katahdin", "female": "Irish cobbler", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Sinnamjak_yield.png", "lw_graph": "graph/Sinnamjak_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2002", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Namseon' : {"name": "Namseon", "korean_name": "남선", "it_number": "it13", "yield": 0, "img": "potatoes/Namseon.png", "pedigree": "pedigree/Namseon.png", "male": "Dakota pearl", "female": "Chugang", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Namseon_yield.png", "lw_graph": "graph/Namseon_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "early", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Geumseon' : {"name": "Geumseon", "korean_name": "금선", "it_number": "it14", "yield": 0, "img": "potatoes/Geumseon.png", "pedigree": "pedigree/Geumseon.png", "male": "DK1-8", "female": "Chuyoung", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Geumseon_yield.png", "lw_graph": "graph/Geumseon_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "2015", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Eunseon' : {"name": "Eunseon", "korean_name": "은선", "it_number": "it15", "yield": 0, "img": "potatoes/Eunseon.png", "pedigree": "pedigree/Eunseon.png", "male": "Dakota pearl", "female": "Chugang", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Eunseon_yield.png", "lw_graph": "graph/Eunseon_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "early", "release_year": "2017", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Suseon' : {"name": "Suseon", "korean_name": "수선", "it_number": "it16", "yield": 0, "img": "potatoes/Suseon.png", "pedigree": "pedigree/Suseon.png", "male": "DK1-109", "female": "GoUn", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Suseon_yield.png", "lw_graph": "graph/Suseon_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jinseon' : {"name": "Jinseon", "korean_name": "진선", "it_number": "it17", "yield": 0, "img": "potatoes/Jinseon.png", "pedigree": "pedigree/Jinseon.png", "male": "DK2-19", "female": "DK1-87", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jinseon_yield.png", "lw_graph": "graph/Jinseon_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "early", "release_year": "2015", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Chubaek' : {"name": "Chubaek", "korean_name": "추백", "it_number": "it18", "yield": 0, "img": "potatoes/Chubaek.png", "pedigree": "pedigree/Chubaek.png", "male": "Superior", "female": "H83011-3", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Chubaek_yield.png", "lw_graph": "graph/Chubaek_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "1999", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Chudong' : {"name": "Chudong", "korean_name": "추동", "it_number": "it19", "yield": 0, "img": "potatoes/Chudong.png", "pedigree": "pedigree/Chudong.png", "male": "Superior", "female": "H83520-3", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Chudong_yield.png", "lw_graph": "graph/Chudong_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "2001", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Chugang' : {"name": "Chugang", "korean_name": "추강", "it_number": "it20", "yield": 0, "img": "potatoes/Chugang.png", "pedigree": "pedigree/Chugang.png", "male": "Superior", "female": "H83005-2", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Chugang_yield.png", "lw_graph": "graph/Chugang_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2002", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Chuyoung' : {"name": "Chuyoung", "korean_name": "추영", "it_number": "it21", "yield": 0, "img": "potatoes/Chuyoung.png", "pedigree": "pedigree/Chuyoung.png", "male": "HRB-31", "female": "Dejima", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Chuyoung_yield.png", "lw_graph": "graph/Chuyoung_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2004", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Bangul' : {"name": "Bangul", "korean_name": "방울", "it_number": "it22", "yield": 0, "img": "potatoes/Bangul.png", "pedigree": "pedigree/Bangul.png", "male": "Superior", "female": "Dejima", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Bangul_yield.png", "lw_graph": "graph/Bangul_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "2010", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Saebong' : {"name": "Saebong", "korean_name": "새봉", "it_number": "it23", "yield": 0, "img": "potatoes/Saebong.png", "pedigree": "pedigree/Saebong.png", "male": "DH09-231", "female": "DK2-8", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Saebong_yield.png", "lw_graph": "graph/Saebong_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "early", "release_year": "2010", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jeseo' : {"name": "Jeseo", "korean_name": "제서", "it_number": "it24", "yield": 0, "img": "potatoes/Jeseo.png", "pedigree": "pedigree/Jeseo.png", "male": "Superior", "female": "S. brevidens", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jeseo_yield.png", "lw_graph": "graph/Jeseo_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2007", "breeding_project": "Jeju provincial Agriculture Research Institute, Korea"},
'Dami' : {"name": "Dami", "korean_name": "다미", "it_number": "it25", "yield": 0, "img": "potatoes/Dami.png", "pedigree": "pedigree/Dami.png", "male": "DK1-98", "female": "DK1-97", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Dami_yield.png", "lw_graph": "graph/Dami_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2015", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jungmo9001' : {"name": "Jungmo9001", "korean_name": "중모9001", "it_number": "it26", "yield": 0, "img": "potatoes/Jungmo9001.png", "pedigree": "pedigree/Jungmo9001.png", "male": "Chubaek", "female": "DK1-83", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jungmo9001_yield.png", "lw_graph": "graph/Jungmo9001_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "2015", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jowon' : {"name": "Jowon", "korean_name": "조운", "it_number": "it27", "yield": 0, "img": "potatoes/Jowon.png", "pedigree": "pedigree/Jowon.png", "male": "Katahdin", "female": "Inje misang", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jowon_yield.png", "lw_graph": "graph/Jowon_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "2001", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jopoong' : {"name": "Jopoong", "korean_name": "조풍", "it_number": "it28", "yield": 0, "img": "potatoes/Jopoong.png", "pedigree": "pedigree/Jopoong.png", "male": "Superior", "female": "Resy", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jopoong_yield.png", "lw_graph": "graph/Jopoong_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "1988", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Seohong' : {"name": "Seohong", "korean_name": "서홍", "it_number": "it29", "yield": 0, "img": "potatoes/Seohong.png", "pedigree": "pedigree/Seohong.png", "male": "93K61-5", "female": "Jashim", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Seohong_yield.png", "lw_graph": "graph/Seohong_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2006", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Haryeong' : {"name": "Haryeong", "korean_name": "하령", "it_number": "it30", "yield": 0, "img": "potatoes/Haryeong.png", "pedigree": "pedigree/Haryeong.png", "male": "Superior", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Haryeong_yield.png", "lw_graph": "graph/Haryeong_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2006", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daeseo' : {"name": "Daeseo", "korean_name": "대서", "it_number": "it31", "yield": 0, "img": "potatoes/Daeseo.png", "pedigree": "pedigree/Daeseo.png", "male": "Lenape", "female": "Wauseon", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daeseo_yield.png", "lw_graph": "graph/Daeseo_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "1976(1995)", "breeding_project": "United States Department of Agriculture, USA"},
'Goun' : {"name": "Goun", "korean_name": "고운", "it_number": "it32", "yield": 0, "img": "potatoes/Goun.png", "pedigree": "pedigree/Goun.png", "male": "Chubaek", "female": "Lemhi russet", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Goun_yield.png", "lw_graph": "graph/Goun_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2006", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Doobaek' : {"name": "Doobaek", "korean_name": "두백", "it_number": "it33", "yield": 0, "img": "potatoes/Doobaek.png", "pedigree": "pedigree/Doobaek.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Doobaek_yield.png", "lw_graph": "graph/Doobaek_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2000", "breeding_project": "Orion company, Korea"},
'Daeji' : {"name": "Daeji", "korean_name": "대지", "it_number": "it34", "yield": 0, "img": "potatoes/Daeji.png", "pedigree": "pedigree/Daeji.png", "male": "Unzen", "female": "Hokkai 31", "alt_name": "", "alt_english_name": "Daejima", "yield_graph": "graph/Daeji_yield.png", "lw_graph": "graph/Daeji_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "late", "release_year": "1971(1978)", "breeding_project": "Nagasaki agricultural research Institute, Japan"},
'Sepoong' : {"name": "Sepoong", "korean_name": "세풍", "it_number": "it35", "yield": 0, "img": "potatoes/Sepoong.png", "pedigree": "pedigree/Sepoong.png", "male": "F58050", "female": "Bake king", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Sepoong_yield.png", "lw_graph": "graph/Sepoong_lw.png", "category": "Korean variety", "market": "French fry", "maturity": "Int", "release_year": "1980(1988)", "breeding_project": "Agricultural Research Institute, New brunswick, Canada"},
'Sumi' : {"name": "Sumi", "korean_name": "수미", "it_number": "it36", "yield": 0, "img": "potatoes/Sumi.png", "pedigree": "pedigree/Sumi.png", "male": "M59-44", "female": "B95-96", "alt_name": "", "alt_english_name": "superior", "yield_graph": "graph/Sumi_yield.png", "lw_graph": "graph/Sumi_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "1961(1978)", "breeding_project": "Wisconsin University, USA"},
'Hongseon' : {"name": "Hongseon", "korean_name": "홍선", "it_number": "it37", "yield": 0, "img": "potatoes/Hongseon.png", "pedigree": "pedigree/Hongseon.png", "male": "H02005-6", "female": "Dakota Rose", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Hongseon_yield.png", "lw_graph": "graph/Hongseon_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "early", "release_year": "2012", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jayoung' : {"name": "Jayoung", "korean_name": "자영", "it_number": "it38", "yield": 0, "img": "potatoes/Jayoung.png", "pedigree": "pedigree/Jayoung.png", "male": "AG34314", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jayoung_yield.png", "lw_graph": "graph/Jayoung_lw.png", "category": "Korean variety", "market": "Pigmented skin/flesh", "maturity": "late", "release_year": "2007", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Hongyoung' : {"name": "Hongyoung", "korean_name": "홍영", "it_number": "it39", "yield": 0, "img": "potatoes/Hongyoung.png", "pedigree": "pedigree/Hongyoung.png", "male": "AG34314", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Hongyoung_yield.png", "lw_graph": "graph/Hongyoung_lw.png", "category": "Korean variety", "market": "Pigmented skin/flesh", "maturity": "Int", "release_year": "2007", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Hongjiseul' : {"name": "Hongjiseul", "korean_name": "홍지슬", "it_number": "it40", "yield": 0, "img": "potatoes/Hongjiseul.png", "pedigree": "pedigree/Hongjiseul.png", "male": "Tamna", "female": "Hongyoung", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Hongjiseul_yield.png", "lw_graph": "graph/Hongjiseul_lw.png", "category": "Korean variety", "market": "Pigmented skin/flesh", "maturity": "Int", "release_year": "2017", "breeding_project": "Jeju provincial Agriculture Research Institute, Korea"},
'Gahwang' : {"name": "Gahwang", "korean_name": "가황", "it_number": "it41", "yield": 0, "img": "potatoes/Gahwang.png", "pedigree": "pedigree/Gahwang.png", "male": "AG54071", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Gahwang_yield.png", "lw_graph": "graph/Gahwang_lw.png", "category": "korean variety", "market": "Table stock", "maturity": "early", "release_year": "2002", "breeding_project": "korean variety"},
'Suji' : {"name": "Suji", "korean_name": "수지", "it_number": "it42", "yield": 0, "img": "potatoes/Suji.png", "pedigree": "pedigree/Suji.png", "male": "Bangul", "female": "Saebong", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Suji_yield.png", "lw_graph": "graph/Suji_lw.png", "category": "korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2018", "breeding_project": "korean variety"},
'Early Fri' : {"name": "Early Fri", "korean_name": "얼리프라이", "it_number": "it43", "yield": 0, "img": "potatoes/Early Fri.png", "pedigree": "pedigree/Early Fri.png", "male": "Rusia-3ho", "female": "Dakota Pearl", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Early Fri_yield.png", "lw_graph": "graph/Early Fri_lw.png", "category": "korean variety", "market": "Table stock", "maturity": "early", "release_year": "2019", "breeding_project": "korean variety"},
'Golden Egg' : {"name": "Golden Egg", "korean_name": "골든에그", "it_number": "it44", "yield": 0, "img": "potatoes/Golden Egg.png", "pedigree": "pedigree/Golden Egg.png", "male": "Daekwan 1-117", "female": "Frontier", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Golden Egg_yield.png", "lw_graph": "graph/Golden Egg_lw.png", "category": "korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2019", "breeding_project": "korean variety"},
'Hichip' : {"name": "Hichip", "korean_name": "하이칩", "it_number": "it45", "yield": 0, "img": "potatoes/Hichip.png", "pedigree": "pedigree/Hichip.png", "male": "Hongseon", "female": "Goun", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Hichip_yield.png", "lw_graph": "graph/Hichip_lw.png", "category": "korean variety", "market": "Chip processing", "maturity": "early", "release_year": "2018", "breeding_project": "korean variety"},
'Jaekyo-P-14' : {"name": "Jaekyo-P-14", "korean_name": "재교p14", "it_number": "it46", "yield": 0, "img": "potatoes/Jaekyo-P-14.png", "pedigree": "pedigree/Jaekyo-P-14.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jaekyo-P-14_yield.png", "lw_graph": "graph/Jaekyo-P-14_lw.png", "category": "Advanced breeding line", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "Jeju provincial Agriculture Research Institute, Korea"},
'Jaekyo-P-15' : {"name": "Jaekyo-P-15", "korean_name": "재교p15", "it_number": "it47", "yield": 0, "img": "potatoes/Jaekyo-P-15.png", "pedigree": "pedigree/Jaekyo-P-15.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Jaekyo-P-15_yield.png", "lw_graph": "graph/Jaekyo-P-15_lw.png", "category": "Advanced breeding line", "market": "Pigmented skin/flesh", "maturity": "-", "release_year": "-", "breeding_project": "Jeju provincial Agriculture Research Institute, Korea"},
'Daekwan2-41' : {"name": "Daekwan2-41", "korean_name": "대관2-41", "it_number": "it48", "yield": 0, "img": "potatoes/Daekwan2-41.png", "pedigree": "pedigree/Daekwan2-41.png", "male": "Daekwan2-8", "female": "AG44077", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-41_yield.png", "lw_graph": "graph/Daekwan2-41_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "early", "release_year": "2013", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-56' : {"name": "Daekwan2-56", "korean_name": "대관2-56", "it_number": "it49", "yield": 0, "img": "potatoes/Daekwan2-56.png", "pedigree": "pedigree/Daekwan2-56.png", "male": "Daeji", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-56_yield.png", "lw_graph": "graph/Daekwan2-56_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2017", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Alan(Daekwan2-57)' : {"name": "Alan(Daekwan2-57)", "korean_name": "아란", "it_number": "it50", "yield": 0, "img": "potatoes/Alan(Daekwan2-57).png", "pedigree": "pedigree/Alan(Daekwan2-57).png", "male": "Dakota Pearl", "female": "Hongseon", "alt_name": "대관2-57", "alt_english_name": "Daekwan2-57", "yield_graph": "graph/Alan(Daekwan2-57)_yield.png", "lw_graph": "graph/Alan(Daekwan2-57)_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2017", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Geumnaru(Daekwan2-58)' : {"name": "Geumnaru(Daekwan2-58)", "korean_name": "금나루", "it_number": "it51", "yield": 0, "img": "potatoes/Geumnaru(Daekwan2-58).png", "pedigree": "pedigree/Geumnaru(Daekwan2-58).png", "male": "Jungmo9001", "female": "Dakota pearl", "alt_name": "대관2-58", "alt_english_name": "Daekwan2-58", "yield_graph": "graph/Geumnaru(Daekwan2-58)_yield.png", "lw_graph": "graph/Geumnaru(Daekwan2-58)_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "Int", "release_year": "2017", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-60' : {"name": "Daekwan2-60", "korean_name": "대관2-60", "it_number": "it52", "yield": 0, "img": "potatoes/Daekwan2-60.png", "pedigree": "pedigree/Daekwan2-60.png", "male": "Daekwan1-119", "female": "GoUn", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-60_yield.png", "lw_graph": "graph/Daekwan2-60_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Chuwon(Daekwan2-62)' : {"name": "Chuwon(Daekwan2-62)", "korean_name": "추원", "it_number": "it53", "yield": 0, "img": "potatoes/Chuwon(Daekwan2-62).png", "pedigree": "pedigree/Chuwon(Daekwan2-62).png", "male": "Daekwan1-122", "female": "Atlantic", "alt_name": "대관2-62", "alt_english_name": "Daekwan2-62", "yield_graph": "graph/Chuwon(Daekwan2-62)_yield.png", "lw_graph": "graph/Chuwon(Daekwan2-62)_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-63' : {"name": "Daekwan2-63", "korean_name": "대관2-63", "it_number": "it54", "yield": 0, "img": "potatoes/Daekwan2-63.png", "pedigree": "pedigree/Daekwan2-63.png", "male": "Daeji", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-63_yield.png", "lw_graph": "graph/Daekwan2-63_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "early", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-65' : {"name": "Daekwan2-65", "korean_name": "대관2-65", "it_number": "it55", "yield": 0, "img": "potatoes/Daekwan2-65.png", "pedigree": "pedigree/Daekwan2-65.png", "male": "JungMo9001", "female": "HaRyeong", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-65_yield.png", "lw_graph": "graph/Daekwan2-65_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-66' : {"name": "Daekwan2-66", "korean_name": "대관2-66", "it_number": "it56", "yield": 0, "img": "potatoes/Daekwan2-66.png", "pedigree": "pedigree/Daekwan2-66.png", "male": "Daekwan1-125", "female": "GoUn", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-66_yield.png", "lw_graph": "graph/Daekwan2-66_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "early", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-67' : {"name": "Daekwan2-67", "korean_name": "대관2-67", "it_number": "it57", "yield": 0, "img": "potatoes/Daekwan2-67.png", "pedigree": "pedigree/Daekwan2-67.png", "male": "Gangseon", "female": "Goun", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-67_yield.png", "lw_graph": "graph/Daekwan2-67_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-68' : {"name": "Daekwan2-68", "korean_name": "대관2-68", "it_number": "it58", "yield": 0, "img": "potatoes/Daekwan2-68.png", "pedigree": "pedigree/Daekwan2-68.png", "male": "Daekwan2-42", "female": "Goun", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-68_yield.png", "lw_graph": "graph/Daekwan2-68_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2020", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan2-69' : {"name": "Daekwan2-69", "korean_name": "대관2-69", "it_number": "it59", "yield": 0, "img": "potatoes/Daekwan2-69.png", "pedigree": "pedigree/Daekwan2-69.png", "male": "Daekwan 1-126", "female": "Hongsun", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan2-69_yield.png", "lw_graph": "graph/Daekwan2-69_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2020", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'DaeKwan1-123' : {"name": "DaeKwan1-123", "korean_name": "대관1-123", "it_number": "it60", "yield": 0, "img": "potatoes/DaeKwan1-123.png", "pedigree": "pedigree/DaeKwan1-123.png", "male": "Dakota rose", "female": "Daekwan1-97", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/DaeKwan1-123_yield.png", "lw_graph": "graph/DaeKwan1-123_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "Int", "release_year": "2012", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'DaeKwan1-129' : {"name": "DaeKwan1-129", "korean_name": "대관1-129", "it_number": "it61", "yield": 0, "img": "potatoes/DaeKwan1-129.png", "pedigree": "pedigree/DaeKwan1-129.png", "male": "P03404-1", "female": "ND2717-6", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/DaeKwan1-129_yield.png", "lw_graph": "graph/DaeKwan1-129_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2013", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daeback(Daekwan1-139)' : {"name": "Daeback(Daekwan1-139)", "korean_name": "대백", "it_number": "it62", "yield": 0, "img": "potatoes/Daeback(Daekwan1-139).png", "pedigree": "pedigree/Daeback(Daekwan1-139).png", "male": "CS09", "female": "Daekwan110", "alt_name": "대관1-139", "alt_english_name": "Daekwan1-139", "yield_graph": "graph/Daeback(Daekwan1-139)_yield.png", "lw_graph": "graph/Daeback(Daekwan1-139)_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Dawon(DaeKwan1-143)' : {"name": "Dawon(DaeKwan1-143)", "korean_name": "다원", "it_number": "it63", "yield": 0, "img": "potatoes/Dawon(DaeKwan1-143).png", "pedigree": "pedigree/Dawon(DaeKwan1-143).png", "male": "Superior", "female": "P05810-4", "alt_name": "대관1-143", "alt_english_name": "Daekwan1-143", "yield_graph": "graph/Dawon(DaeKwan1-143)_yield.png", "lw_graph": "graph/Dawon(DaeKwan1-143)_lw.png", "category": "Korean variety", "market": "Chip processing", "maturity": "late", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-144' : {"name": "Daekwan1-144", "korean_name": "대관1-144", "it_number": "it64", "yield": 0, "img": "potatoes/Daekwan1-144.png", "pedigree": "pedigree/Daekwan1-144.png", "male": "Atlantic", "female": "HaRyeong", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-144_yield.png", "lw_graph": "graph/Daekwan1-144_lw.png", "category": "Advanced breeding line", "market": "Chip processing", "maturity": "Int", "release_year": "2016", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Dagam(Daekwan1-145)' : {"name": "Dagam(Daekwan1-145)", "korean_name": "다감", "it_number": "it65", "yield": 0, "img": "potatoes/Dagam(Daekwan1-145).png", "pedigree": "pedigree/Dagam(Daekwan1-145).png", "male": "Superior", "female": "CIP391047.34", "alt_name": "대관1-145", "alt_english_name": "Daekwan1-145", "yield_graph": "graph/Dagam(Daekwan1-145)_yield.png", "lw_graph": "graph/Dagam(Daekwan1-145)_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-146' : {"name": "Daekwan1-146", "korean_name": "대관1-146", "it_number": "it66", "yield": 0, "img": "potatoes/Daekwan1-146.png", "pedigree": "pedigree/Daekwan1-146.png", "male": "Superior", "female": "CIP391047.34", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-146_yield.png", "lw_graph": "graph/Daekwan1-146_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Poseuli(Daekwan1-148)' : {"name": "Poseuli(Daekwan1-148)", "korean_name": "포슬이", "it_number": "it67", "yield": 0, "img": "potatoes/Poseuli(Daekwan1-148).png", "pedigree": "pedigree/Poseuli(Daekwan1-148).png", "male": "Superior", "female": "Haryeong", "alt_name": "대관1-148", "alt_english_name": "Daekwan1-148", "yield_graph": "graph/Poseuli(Daekwan1-148)_yield.png", "lw_graph": "graph/Poseuli(Daekwan1-148)_lw.png", "category": "Korean variety", "market": "Flake", "maturity": "early", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-149' : {"name": "Daekwan1-149", "korean_name": "대관1-149", "it_number": "it68", "yield": 0, "img": "potatoes/Daekwan1-149.png", "pedigree": "pedigree/Daekwan1-149.png", "male": "AG4185", "female": "Superior", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-149_yield.png", "lw_graph": "graph/Daekwan1-149_lw.png", "category": "Advanced breeding line", "market": "French fries, flake", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-152' : {"name": "Daekwan1-152", "korean_name": "대관1-152", "it_number": "it69", "yield": 0, "img": "potatoes/Daekwan1-152.png", "pedigree": "pedigree/Daekwan1-152.png", "male": "P05849-10", "female": "HarRyeong", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-152_yield.png", "lw_graph": "graph/Daekwan1-152_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "Int", "release_year": "2018", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-153' : {"name": "Daekwan1-153", "korean_name": "대관1-153", "it_number": "it70", "yield": 0, "img": "potatoes/Daekwan1-153.png", "pedigree": "pedigree/Daekwan1-153.png", "male": "Duback", "female": "Superior", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-153_yield.png", "lw_graph": "graph/Daekwan1-153_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "early", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-158' : {"name": "Daekwan1-158", "korean_name": "대관1-158", "it_number": "it71", "yield": 0, "img": "potatoes/Daekwan1-158.png", "pedigree": "pedigree/Daekwan1-158.png", "male": "Degjiree", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-158_yield.png", "lw_graph": "graph/Daekwan1-158_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "Int", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Jangwon(Daekwan1-159)' : {"name": "Jangwon(Daekwan1-159)", "korean_name": "장원", "it_number": "it72", "yield": 0, "img": "potatoes/Jangwon(Daekwan1-159).png", "pedigree": "pedigree/Jangwon(Daekwan1-159).png", "male": "Duback", "female": "Atlantic", "alt_name": "대관1-159", "alt_english_name": "Daekwan1-159", "yield_graph": "graph/Jangwon(Daekwan1-159)_yield.png", "lw_graph": "graph/Jangwon(Daekwan1-159)_lw.png", "category": "Korean variety", "market": "Table stock", "maturity": "Int", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Daekwan1-160' : {"name": "Daekwan1-160", "korean_name": "대관1-160", "it_number": "it73", "yield": 0, "img": "potatoes/Daekwan1-160.png", "pedigree": "pedigree/Daekwan1-160.png", "male": "Duback", "female": "Atlantic", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Daekwan1-160_yield.png", "lw_graph": "graph/Daekwan1-160_lw.png", "category": "Advanced breeding line", "market": "Table stock", "maturity": "early", "release_year": "2019", "breeding_project": "Highland Agriculture Research Institute, Korea"},
'Spunta' : {"name": "Spunta", "korean_name": "Spunta", "it_number": "it74", "yield": 0, "img": "potatoes/Spunta.png", "pedigree": "pedigree/Spunta.png", "male": "USDA 96-56", "female": "Bea ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Spunta_yield.png", "lw_graph": "graph/Spunta_lw.png", "category": "Netherlands variety", "market": "Table stock", "maturity": "Int", "release_year": "1969", "breeding_project": "J. Olden-burger Hettema"},
'Raja' : {"name": "Raja", "korean_name": "Raja", "it_number": "it75", "yield": 0, "img": "potatoes/Raja.png", "pedigree": "pedigree/Raja.png", "male": "CEB70-162-23", "female": "Elvira", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Raja_yield.png", "lw_graph": "graph/Raja_lw.png", "category": "Netherlands variety", "market": "-", "maturity": "-", "release_year": "1994", "breeding_project": "CEBECO"},
'Eba' : {"name": "Eba", "korean_name": "Eba", "it_number": "it76", "yield": 0, "img": "potatoes/Eba.png", "pedigree": "pedigree/Eba.png", "male": "Bato", "female": "Eersteling", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Eba_yield.png", "lw_graph": "graph/Eba_lw.png", "category": "Netherlands variety", "market": "Frenech fries", "maturity": "Int", "release_year": "1966", "breeding_project": "G. Kuik"},
'Elkana' : {"name": "Elkana", "korean_name": "Elkana", "it_number": "it77", "yield": 0, "img": "potatoes/Elkana.png", "pedigree": "pedigree/Elkana.png", "male": "Prominent", "female": "Mara", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Elkana_yield.png", "lw_graph": "graph/Elkana_lw.png", "category": "Netherlands variety", "market": "Starch processing", "maturity": "late", "release_year": "1976", "breeding_project": "Kweekinsti-tuut Karna Avebe Agro"},
'Sante' : {"name": "Sante", "korean_name": "Sante", "it_number": "it78", "yield": 0, "img": "potatoes/Sante.png", "pedigree": "pedigree/Sante.png", "male": "SVP AM 66-42", "female": "Y66-13-636 ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Sante_yield.png", "lw_graph": "graph/Sante_lw.png", "category": "Netherlands variety", "market": "Table stock", "maturity": "Int", "release_year": "1981", "breeding_project": "J.Vegter Agrico B.V.Cooperatieve Handlelsvereniging"},
'Tanja' : {"name": "Tanja", "korean_name": "Tanja", "it_number": "it79", "yield": 0, "img": "potatoes/Tanja.png", "pedigree": "pedigree/Tanja.png", "male": "Roypta Y.14", "female": "Eersteling", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Tanja_yield.png", "lw_graph": "graph/Tanja_lw.png", "category": "German variety", "market": "-", "maturity": "Int", "release_year": "1988", "breeding_project": "IPK"},
'Papa Negras' : {"name": "Papa Negras", "korean_name": "Papa Negras", "it_number": "it80", "yield": 0, "img": "potatoes/Papa Negras.png", "pedigree": "pedigree/Papa Negras.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Papa Negras_yield.png", "lw_graph": "graph/Papa Negras_lw.png", "category": "Spain variety", "market": "Pigmented", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'Laura' : {"name": "Laura", "korean_name": "Laura", "it_number": "it81", "yield": 0, "img": "potatoes/Laura.png", "pedigree": "pedigree/Laura.png", "male": "Katahdin", "female": "Saskia", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Laura_yield.png", "lw_graph": "graph/Laura_lw.png", "category": "Spain variety", "market": "Chip processing", "maturity": "Int", "release_year": "1967", "breeding_project": "Neiker"},
'May Queen' : {"name": "May Queen", "korean_name": "May Queen", "it_number": "it82", "yield": 0, "img": "potatoes/May Queen.png", "pedigree": "pedigree/May Queen.png", "male": "S.rybinii", "female": "Herald", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/May Queen_yield.png", "lw_graph": "graph/May Queen_lw.png", "category": "UK variety", "market": "Table stock", "maturity": "early", "release_year": "1890", "breeding_project": "United kingdom of great britain"},
'Pentland Crown' : {"name": "Pentland Crown", "korean_name": "Pentland Crown", "it_number": "it83", "yield": 0, "img": "potatoes/Pentland Crown.png", "pedigree": "pedigree/Pentland Crown.png", "male": "11-79", "female": "G.414", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Pentland Crown_yield.png", "lw_graph": "graph/Pentland Crown_lw.png", "category": "UK variety", "market": "Table stock", "maturity": "Int", "release_year": "1958", "breeding_project": "SCRI (S.E.E.R.A.D.)"},
'Pentland Dell' : {"name": "Pentland Dell", "korean_name": "Pentland Dell", "it_number": "it84", "yield": 0, "img": "potatoes/Pentland Dell.png", "pedigree": "pedigree/Pentland Dell.png", "male": " Roslin Sasamua", "female": "Roslin Chania", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Pentland Dell_yield.png", "lw_graph": "graph/Pentland Dell_lw.png", "category": "UK variety", "market": "Frency fries", "maturity": "Int", "release_year": "1960", "breeding_project": "SCRI (S.E.E.R.A.D.)"},
'Dark Red Norland_hari' : {"name": "Dark Red Norland_hari", "korean_name": "Dark Red Norland_hari", "it_number": "it85", "yield": 0, "img": "potatoes/Dark Red Norland_hari.png", "pedigree": "pedigree/Dark Red Norland_hari.png", "male": " ND626", "female": "Red kote ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Dark Red Norland_hari_yield.png", "lw_graph": "graph/Dark Red Norland_hari_lw.png", "category": "USA variety", "market": "Pigmented skin", "maturity": "early", "release_year": "1957", "breeding_project": "North Dakota University"},
'Penobscot' : {"name": "Penobscot", "korean_name": "Penobscot", "it_number": "it86", "yield": 0, "img": "potatoes/Penobscot.png", "pedigree": "pedigree/Penobscot.png", "male": "Katahdin", "female": "X927-3 ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Penobscot_yield.png", "lw_graph": "graph/Penobscot_lw.png", "category": "USA variety", "market": "-", "maturity": "Int", "release_year": "1963", "breeding_project": "-"},
'Bake King' : {"name": "Bake King", "korean_name": "Bake King", "it_number": "it87", "yield": 0, "img": "potatoes/Bake King.png", "pedigree": "pedigree/Bake King.png", "male": "Green mountain", "female": "Merrimack", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Bake King_yield.png", "lw_graph": "graph/Bake King_lw.png", "category": "USA variety", "market": "Table stock", "maturity": "-", "release_year": "1967", "breeding_project": "Arche Noah"},
'Triumph' : {"name": "Triumph", "korean_name": "Triumph", "it_number": "it88", "yield": 0, "img": "potatoes/Triumph.png", "pedigree": "pedigree/Triumph.png", "male": "Early rose", "female": "Peerless", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Triumph_yield.png", "lw_graph": "graph/Triumph_lw.png", "category": "USA variety", "market": "Pigmented", "maturity": "early", "release_year": "1878", "breeding_project": "B.K.Bliss & Sons (New York)"},
'Rosa' : {"name": "Rosa", "korean_name": "Rosa", "it_number": "it89", "yield": 0, "img": "potatoes/Rosa.png", "pedigree": "pedigree/Rosa.png", "male": "Wauseon", "female": "J.171-8", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Rosa_yield.png", "lw_graph": "graph/Rosa_lw.png", "category": "USA variety", "market": "Table stock", "maturity": "late", "release_year": "1980", "breeding_project": "USA"},
'Russet Norkotah_hari' : {"name": "Russet Norkotah_hari", "korean_name": "Russet Norkotah_hari", "it_number": "it90", "yield": 0, "img": "potatoes/Russet Norkotah_hari.png", "pedigree": "pedigree/Russet Norkotah_hari.png", "male": "ND9687-5Russ", "female": "ND9526-4 Russ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Russet Norkotah_hari_yield.png", "lw_graph": "graph/Russet Norkotah_hari_lw.png", "category": "USA variety", "market": "Table stock", "maturity": "early", "release_year": "1987", "breeding_project": "North Dakota University"},
'Dakota Pearl_hari' : {"name": "Dakota Pearl_hari", "korean_name": "Dakota Pearl_hari", "it_number": "it91", "yield": 0, "img": "potatoes/Dakota Pearl_hari.png", "pedigree": "pedigree/Dakota Pearl_hari.png", "male": "ND944-6", "female": "ND1118-1", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Dakota Pearl_hari_yield.png", "lw_graph": "graph/Dakota Pearl_hari_lw.png", "category": "USA variety", "market": "Table stock/Chip processing", "maturity": "Int", "release_year": "1999", "breeding_project": "University/ND"},
'Gemchip_hari' : {"name": "Gemchip_hari", "korean_name": "Gemchip_hari", "it_number": "it92", "yield": 0, "img": "potatoes/Gemchip_hari.png", "pedigree": "pedigree/Gemchip_hari.png", "male": "ND5737-3", "female": "BR5960-9", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Gemchip_hari_yield.png", "lw_graph": "graph/Gemchip_hari_lw.png", "category": "USA variety", "market": "Chip processing", "maturity": "Int", "release_year": "1989", "breeding_project": "USDA Maine"},
'Norking Russet' : {"name": "Norking Russet", "korean_name": "Norking Russet", "it_number": "it93", "yield": 0, "img": "potatoes/Norking Russet.png", "pedigree": "pedigree/Norking Russet.png", "male": "ND9567-2 Russ", "female": "Nooksack", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Norking Russet_yield.png", "lw_graph": "graph/Norking Russet_lw.png", "category": "USA variety", "market": "Frency fries", "maturity": "Int", "release_year": "1985", "breeding_project": "North Dakota University"},
'Red Moon_hari' : {"name": "Red Moon_hari", "korean_name": "Red Moon_hari", "it_number": "it94", "yield": 0, "img": "potatoes/Red Moon_hari.png", "pedigree": "pedigree/Red Moon_hari.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Red Moon_hari_yield.png", "lw_graph": "graph/Red Moon_hari_lw.png", "category": "Japanese variety", "market": "Pigmented", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'Norin1_hari' : {"name": "Norin1_hari", "korean_name": "Norin1_hari", "it_number": "it95", "yield": 0, "img": "potatoes/Norin1_hari.png", "pedigree": "pedigree/Norin1_hari.png", "male": "Deodara", "female": "Irish Cobbler", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Norin1_hari_yield.png", "lw_graph": "graph/Norin1_hari_lw.png", "category": "Japanese variety", "market": "Table stock", "maturity": "-", "release_year": "1937", "breeding_project": "JPN"},
'Arachy' : {"name": "Arachy", "korean_name": "Arachy", "it_number": "it96", "yield": 0, "img": "potatoes/Arachy.png", "pedigree": "pedigree/Arachy.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Arachy_yield.png", "lw_graph": "graph/Arachy_lw.png", "category": "Brazil variety", "market": "-", "maturity": "Int", "release_year": "-", "breeding_project": "O.J.Book IAC"},
'Red Rascal' : {"name": "Red Rascal", "korean_name": "Red Rascal", "it_number": "it97", "yield": 0, "img": "potatoes/Red Rascal.png", "pedigree": "pedigree/Red Rascal.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Red Rascal_yield.png", "lw_graph": "graph/Red Rascal_lw.png", "category": "New Zealand variety", "market": "Pigmented", "maturity": "late", "release_year": "1993", "breeding_project": "CFR(NZ)"},
'Belarus3' : {"name": "Belarus3", "korean_name": "Belarus3", "it_number": "it98", "yield": 0, "img": "potatoes/Belarus3.png", "pedigree": "pedigree/Belarus3.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Belarus3_yield.png", "lw_graph": "graph/Belarus3_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "Belarus"},
'Russia12' : {"name": "Russia12", "korean_name": "Russia12", "it_number": "it99", "yield": 0, "img": "potatoes/Russia12.png", "pedigree": "pedigree/Russia12.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Russia12_yield.png", "lw_graph": "graph/Russia12_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "Russia"},
'Tamasha' : {"name": "Tamasha", "korean_name": "Tamasha", "it_number": "it100", "yield": 0, "img": "potatoes/Tamasha.png", "pedigree": "pedigree/Tamasha.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Tamasha_yield.png", "lw_graph": "graph/Tamasha_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "Kazakhstan"},
'Kexin4' : {"name": "Kexin4", "korean_name": "Kexin4", "it_number": "it101", "yield": 0, "img": "potatoes/Kexin4.png", "pedigree": "pedigree/Kexin4.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/Kexin4_yield.png", "lw_graph": "graph/Kexin4_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "China"},
'76B54-2' : {"name": "76B54-2", "korean_name": "76B54-2", "it_number": "it102", "yield": 0, "img": "potatoes/76B54-2.png", "pedigree": "pedigree/76B54-2.png", "male": "Platle", "female": "Cherokee ", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/76B54-2_yield.png", "lw_graph": "graph/76B54-2_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "", "breeding_project": "-"},
'HAt-22' : {"name": "HAt-22", "korean_name": "HAt-22", "it_number": "it103", "yield": 0, "img": "potatoes/HAt-22.png", "pedigree": "pedigree/HAt-22.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/HAt-22_yield.png", "lw_graph": "graph/HAt-22_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'CO09551_7W' : {"name": "CO09551_7W", "korean_name": "CO09551_7W", "it_number": "it104", "yield": 0, "img": "potatoes/CO09551_7W.png", "pedigree": "pedigree/CO09551_7W.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/CO09551_7W_yield.png", "lw_graph": "graph/CO09551_7W_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'CO97043_14W' : {"name": "CO97043_14W", "korean_name": "CO97043_14W", "it_number": "it105", "yield": 0, "img": "potatoes/CO97043_14W.png", "pedigree": "pedigree/CO97043_14W.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/CO97043_14W_yield.png", "lw_graph": "graph/CO97043_14W_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'R5' : {"name": "R5", "korean_name": "R5", "it_number": "it106", "yield": 0, "img": "potatoes/R5.png", "pedigree": "pedigree/R5.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/R5_yield.png", "lw_graph": "graph/R5_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'R6' : {"name": "R6", "korean_name": "R6", "it_number": "it107", "yield": 0, "img": "potatoes/R6.png", "pedigree": "pedigree/R6.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/R6_yield.png", "lw_graph": "graph/R6_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'1833' : {"name": "1833", "korean_name": "1833", "it_number": "it108", "yield": 0, "img": "potatoes/1833.png", "pedigree": "pedigree/1833.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/1833_yield.png", "lw_graph": "graph/1833_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'2048' : {"name": "2048", "korean_name": "2048", "it_number": "it109", "yield": 0, "img": "potatoes/2048.png", "pedigree": "pedigree/2048.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/2048_yield.png", "lw_graph": "graph/2048_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"},
'B9482-3' : {"name": "B9482-3", "korean_name": "B9482-3", "it_number": "it110", "yield": 0, "img": "potatoes/B9482-3.png", "pedigree": "pedigree/B9482-3.png", "male": "-", "female": "-", "alt_name": "", "alt_english_name": "", "yield_graph": "graph/B9482-3_yield.png", "lw_graph": "graph/B9482-3_lw.png", "category": "-", "market": "-", "maturity": "-", "release_year": "-", "breeding_project": "-"}
}


search_mapping = {key.lower(): key for key in cultivars_info}

for key, value in cultivars_info.items():
    search_mapping[value['korean_name']] = key
    #search_mapping.setdefault(value['it_number'], key)

    if 'alt_english_name' in value and value['alt_english_name']:
        search_mapping[value['alt_english_name'].lower()] = key

    if 'alt_name' in value and value['alt_name']:
        search_mapping[value['alt_name']] = key

@app.route('/')
def home():
    return render_template('main_page.html')

@app.route('/cultivar_list')
def cultivar_list():
    return render_template('cultivar_list.html')

@app.route('/search', methods=['POST'])
def search():
    search_query = escape(request.form.get('name', '').strip().lower())

    if not search_query:
        return redirect(url_for('home'))

    if search_query in search_mapping:
        return redirect(url_for('results', query=search_mapping[search_query]))

    matched_cultivars = [search_mapping[key] for key in search_mapping if search_query in key.lower()]
    matching_cultivars = []
    for each in matched_cultivars:
        if each not in matching_cultivars:
            matching_cultivars.append(each)
    matched_cultivars = matching_cultivars


    if not matched_cultivars:
        return redirect(url_for('no_results'))

    return redirect(url_for('results', query=",".join(matched_cultivars)))

@app.route('/results')
def results():
    query = request.args.get('query', '')

    cultivar_keys = query.split(",")
    cultivar_data_list = [cultivars_info.get(key) for key in cultivar_keys if key in cultivars_info]
    if not cultivar_data_list:
        return redirect(url_for('no_results'))

    return render_template('search_results.html', cultivars=cultivar_data_list)

@app.route('/no_results')
def no_results():
    return render_template('no_results.html')

@app.route('/cultivar/<name>')
def cultivar_detail(name):
    name = name.lower()
    if name in search_mapping:
        name = search_mapping[name]
    cultivar_data = cultivars_info.get(name)
    if not cultivar_data:
        return redirect(url_for('no_results'))
    return render_template('cultivar_detail.html', cultivar=cultivar_data)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=False)
